name: branch-build
permissions: read-all

on:
  push:
    branches-ignore:
      - master

jobs:
  branch-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y gcc-12 g++-12 make ragel lemon cmake

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: CC=gcc-12 CXX=g++-12 cmake -DDISABLE_CLANG_TIDY=YES -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build
