name: Branch Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y gcc-12 g++-12 build-essential ragel lemon cmake

    - name: Checkout Repository
      uses: actions/checkout@v3
    - run: git fetch --tags
  
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build
